// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdM_jhHtEGpOXJ-mZcZrd3Gzxe7VQNTdg',
    appId: '1:988351086920:web:288c1adb06090cbf1db37d',
    messagingSenderId: '988351086920',
    projectId: 'mim-4cba4',
    authDomain: 'mim-4cba4.firebaseapp.com',
    storageBucket: 'mim-4cba4.firebasestorage.app',
    measurementId: 'G-1HDDBFT0KS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgExgJih_LKn5WYJfoRDIX-c9fddM9Qh4',
    appId: '1:988351086920:android:b4951724d8c852f81db37d',
    messagingSenderId: '988351086920',
    projectId: 'mim-4cba4',
    storageBucket: 'mim-4cba4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANKgWOA5dalqq98Ay0eRvuwt9o4FjaDIQ',
    appId: '1:988351086920:ios:e4487bf6fad16a011db37d',
    messagingSenderId: '988351086920',
    projectId: 'mim-4cba4',
    storageBucket: 'mim-4cba4.firebasestorage.app',
    iosBundleId: 'com.example.miniGram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANKgWOA5dalqq98Ay0eRvuwt9o4FjaDIQ',
    appId: '1:988351086920:ios:e4487bf6fad16a011db37d',
    messagingSenderId: '988351086920',
    projectId: 'mim-4cba4',
    storageBucket: 'mim-4cba4.firebasestorage.app',
    iosBundleId: 'com.example.miniGram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdM_jhHtEGpOXJ-mZcZrd3Gzxe7VQNTdg',
    appId: '1:988351086920:web:16b517b7fcf800f61db37d',
    messagingSenderId: '988351086920',
    projectId: 'mim-4cba4',
    authDomain: 'mim-4cba4.firebaseapp.com',
    storageBucket: 'mim-4cba4.firebasestorage.app',
    measurementId: 'G-ZJC4K932NH',
  );
}
